######################################################################
# Automatically generated by qmake (3.0) mer. juin 12 18:11:13 2019
######################################################################

TEMPLATE = app
TARGET = kyt-kat
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp

QT	+= widgets
